const REQUEST = "REQUEST";
const SUCCES = "SUCCES";
const FAILURE = "FAILURE";
const POSTREQUEST = "POSTREQUEST";
const POSTSUCCESS = "POSTSUCESS";
const DELETEREQUSET = "DELETEREQUEST";
const DELETESUCCESS = "DELETESUCCESS";
const GETONEUSERREQUEST = "GETONEUSERREQUEST";
const GETONEUSERSUCCESS = "GETONEUSERSUCCESS";
const UPDATEREQUEST = "UPDATEREQUEST";
const UPDATESUCCESS = "UPDATESUCCESS";

module.exports = {
  REQUEST: REQUEST,
  SUCCES: SUCCES,
  FAILURE: FAILURE,
  POSTREQUEST: POSTREQUEST,
  POSTSUCCESS: POSTSUCCESS,
  DELETEREQUEST: DELETEREQUSET,
  DELETESUCCESS: DELETESUCCESS,
  GETONEUSERREQUEST: GETONEUSERREQUEST,
  GETONEUSERSUCCESS: GETONEUSERSUCCESS,
  UPDATEREQUEST: UPDATEREQUEST,
  UPDATESUCCESS: UPDATESUCCESS,
};
